name: Error notification

permissions: 
    contents: write
    issues: write 
    
on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
      error_messages:
        required: true
        type: string

jobs:
  notify_error:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Validation Failed: ${{ inputs.workflow_name }}`,
              body: `Error in workflow: ${{ inputs.workflow_name }}\n\nCommit: ${{ github.sha }}\nBranch: ${{ github.ref }}\nAuthor: ${{ github.actor }}\n\nError(s):\n${{ inputs.error_messages }}\n\n[View workflow run](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})\n\nPlease review the errors above within the validator workflow, fix your submission, and push your changes to re-run validation.`
            })