name: Move Validated Posts

on:
  workflow_run:
    workflows: ["Validate New Tactics"]
    types:
      - completed

permissions:
  contents: write

jobs:
  move-tactics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main
      - name: Set git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Move validated tactics to category subfolders
        run: |
          echo "Listing files in docs/_new_posts before move:"
          ls -l docs/_new_posts || echo "No files found."
          moved_any=false
          shopt -s nullglob
          for file in docs/_new_posts/*.md docs/_new_posts/*.markdown; do
            [ -e "$file" ] || continue
            echo "Processing $file..."
            category=$(awk '
              /^categories:/ {in_categories=1; next}
              in_categories && /^ *- / {
                sub(/^ *- /, "", $0); print $0; exit
              }
              in_categories && NF && !/^ / {in_categories=0}
            ' "$file" | xargs)
            if [ -z "$category" ]; then
              echo "No category found in $file, skipping and NOT deleting."
              continue
            fi
            mkdir -p "docs/_posts/$category"
            mv "$file" "docs/_posts/$category/"
            echo "Moved $file to docs/_posts/$category/"
            moved_any=true
          done
          echo "Listing files in docs/_new_posts after move:"
          ls -l docs/_new_posts || echo "No files left."
          if $moved_any; then
            git add docs/_posts
            git rm -r docs/_new_posts || true
            git commit -m "Move validated tactics to category subfolders in _posts" || echo "No changes to commit"
            git push
          else
            echo "No files were moved. Not deleting docs/_new_posts."
            exit 1
          fi