name: Move Validated Posts

on:
  push:
    branches:
      - main
      - test-tactic

permissions:
  contents: write

jobs:
  move-tactics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Move validated tactics
        run: |
          mkdir -p docs/_posts
          if [ -d docs/_new_posts ]; then
            mv docs/_new_posts/* docs/_posts/ 2>/dev/null || true
          fi

      - name: Ensure category files exist
        run: |
          for file in docs/_posts/*.md docs/_posts/*.markdown; do
            [ -e "$file" ] || continue
            # Extract categories from YAML front matter
            categories=$(awk '/^categories:/,/^[^ ]/' "$file" | grep -v '^categories:' | sed 's/^- //' | tr -d '\r')
            for category in $categories; do
              catfile="docs/categories/${category}.md"
              if [ ! -f "$catfile" ]; then
                cat <<EOF > "$catfile"
cat <<EOF > "$catfile"
---
category-name: "$category"
category-description: "Description for $category"
category-type: ""
---
EOF
                echo "Created category file: $catfile"
              fi
            done
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/_posts docs/categories
          git rm -r docs/_new_posts || true
          git commit -m "Move validated tactics to _posts and ensure category files" || echo "No changes to commit"
          git push