name: Post Update Handler

on:
  push:
    paths:
      - 'docs/_posts/**/*.md'
      - 'docs/_posts/**/*.markdown'
  pull_request:
    paths:
      - 'docs/_posts/**/*.md'
      - 'docs/_posts/**/*.markdown'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Validate existing posts for any changes
      - name: Validate posts
        run: node validator.js docs/_posts

      # Fix markdown schema
      - name: Fix markdown schema
        run: node fix_markdown_schema.js