name: Validate New Tactics

on:
  push:
    branches:
      - main
    paths:
      - 'docs/_posts/**'
      - 'docs/_new_posts/**'
      - 'validator.js'
      - 'tactic.field.json'
      - '.github/workflows/tactic-validation.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/_posts/**'
      - 'docs/_new_posts/**'
      - 'validator.js'
      - 'tactic.field.json'
      - '.github/workflows/tactic-validation.yml'

permissions:
  contents: write
  issues: write
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run validation script
        run: node validator.js

      - name: Check for new posts
        id: new_posts_check
        uses: tj-actions/changed-files@v44
        with:
          files: |
            docs/_new_posts/**

      - name: Generate new tags
        if: steps.new_posts_check.outputs.any_changed == 'true'
        run: node new_tag_generator.js

      - name: Commit and push new tag files
        if: steps.new_posts_check.outputs.any_changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/tags/
          git commit -m "Auto-generate missing tag files" || echo "No changes to commit"
          git push

  notify_on_error:
    needs: validate
    if: failure()
    uses: ./.github/workflows/error-notification.yml
    with:
      workflow_name: ${{ github.workflow }}
      error_messages: "Tactic validation failed. See the logs for additional information."